FROM node:16-slim
ARG FOLDER=virta
EXPOSE 4000
WORKDIR /src
COPY ${FOLDER} ${FOLDER}
COPY virta.ts index.ts
COPY src src
COPY constants.ts constants.ts
COPY websocket.ts websocket.ts
COPY package.json package.json
COPY tsconfig.json tsconfig.json
COPY types.d.ts types.d.ts
ARG FOLDER
RUN npm i \
&& cd $FOLDER \
&& npm i
#WORKDIR /src/${FOLDER}
ARG FOLDER
RUN ls -lha \
&& npm run build_endorser \
&& cd $FOLDER \
&& rm -rf node_modules
WORKDIR /src
RUN ls -lha bin
CMD [ "node",  "bin/index.js" ]
