FROM node:16-slim
ARG FOLDER=idp
ENV FOLDER=${FOLDER}
EXPOSE 4000
WORKDIR /src
COPY ${FOLDER} ${FOLDER}
COPY identityprovider.ts index.ts
COPY src src
COPY constants.ts constants.ts
COPY websocket.ts websocket.ts
COPY package.json package.json
COPY tsconfig.json tsconfig.json
COPY types.d.ts types.d.ts
RUN npm i \
&& cd $FOLDER \
&& npm i
#WORKDIR /src/${FOLDER}

RUN ls -lha \
&& npm run build_idp \
&& cd $FOLDER \
&& rm -rf node_modules
#&& cd .. \
#&& ls -lha
#WORKDIR /src
RUN ls -lha bin
CMD [ "node",  "bin/index.js" ]
