FROM node:16-slim
EXPOSE 4000
WORKDIR /src
COPY webhook.ts index.ts
COPY package.json package.json
COPY tsconfig.json tsconfig.json
RUN npm i && \
npm run build && \
ls -lha
CMD [ "node",  "bin/index.js" ]
