FROM node:16-slim
ARG FOLDER=virta
WORKDIR /src
COPY ${FOLDER}  .
COPY api.ts api.ts
COPY websocket.ts websocket.ts
WORKDIR ${FOLDER}
COPY package.json package.json
COPY tsconfig.json tsconfig.json
RUN npm i && \
npm run build && \
ls -lha
CMD [ "node",  "bin/index.js" ]